{
  "swagger": "2.0",
  "info": {
    "description": "This is a simple user login API",
    "title": "[REST] User Login API",
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/users": {
      "post": {
        "description": "create User",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Create User",
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/users/CreateUserPointerSliceToNonPointerResponse": {
      "post": {
        "description": "create User Pointer Slice To Non Pointer Response",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Create User Pointer Slice To Non Pointer Response",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/users/CreateUserPointerSliceToNonPointerSliceResponse": {
      "post": {
        "description": "create User Pointer Slice To Non Pointer Slice Response",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Create User Pointer Slice To Non Pointer Slice Response",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/users/CreateUserPointerSliceToPointerResponse": {
      "post": {
        "description": "create User Pointer Slice To Pointer Response",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Create User Pointer Slice To Pointer Response",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUserStruct"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/users/CreateUserPointerSliceToSliceResponse": {
      "post": {
        "description": "create User Pointer Slice To Slice Response",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Create User Pointer Slice To Slice Response",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/users/CreateUserStructToNonPointerResponse": {
      "post": {
        "description": "create User Struct To Non Pointer Response",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Create User Struct To Non Pointer Response",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUserStruct"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/users/CreateUserStructToNonPointerSliceResponse": {
      "post": {
        "description": "create User Struct To Non Pointer Response",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Create User Struct To Non Pointer Response",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUserStruct"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/users/CreateUserStructToPointerResponse": {
      "post": {
        "description": "create User Struct To Pointer Response",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Create User Struct To Pointer Response",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUserStruct"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/users/CreateUserStructToSliceResponse": {
      "post": {
        "description": "create User Struct To Slice Response",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Create User Struct To Slice Response",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUserStruct"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/users/NotWork_CreateUserSliceToPointerResponse": {
      "post": {
        "description": "not Work_ Create User Slice To Pointer Response",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Not Work_ Create User Slice To Pointer Response",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/users/{id}": {
      "put": {
        "description": "update User",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Update User",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUserRequest"
            }
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of the resource",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "delete": {
        "description": "delete User",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Delete User",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/int"
            }
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of the resource",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    }
  },
  "definitions": {
    "": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "update_email": {
            "description": "Update the email of the user",
            "type": "string",
            "example": "johnny@example.com"
          },
          "update_username": {
            "description": "Update the username of the user",
            "type": "string",
            "example": "johnny_bravo"
          }
        }
      }
    },
    "CreateUserStruct": {
      "type": "object",
      "properties": {
        "update_email": {
          "description": "Update the email of the user",
          "type": "string",
          "example": "johnny@example.com"
        },
        "update_username": {
          "description": "Update the username of the user",
          "type": "string",
          "example": "johnny_bravo"
        }
      }
    },
    "UpdateUserRequest": {
      "type": "object",
      "properties": {
        "update_email": {
          "description": "Update the email of the user",
          "type": "string",
          "example": "johnny@example.com"
        },
        "update_username": {
          "description": "Update the username of the user",
          "type": "string",
          "example": "johnny_bravo"
        }
      }
    },
    "int": {
      "type": "integer",
      "format": "int64"
    }
  }
}