{
  "swagger": "2.0",
  "info": {
    "description": "API for managing users",
    "title": "User Management API",
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/users": {
      "post": {
        "description": "Create a new main.main.createuser.func2",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "F U N C 2",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUserRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/User"
            },
            "examples": {
              "application/json": {
                "id": 0,
                "username": "",
                "email": "",
                "created_at": "0001-01-01T00:00:00Z"
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "put": {
        "description": "Update existing main.main.updateuser.func4",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "F U N C 4",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of the resource",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "CreateUserRequest": {
      "type": "object",
      "required": [
        "username",
        "email"
      ],
      "properties": {
        "email": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "id",
        "username",
        "email"
      ],
      "properties": {
        "email": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "username": {
          "type": "string"
        }
      }
    }
  }
}