{
  "swagger": "2.0",
  "info": {
    "description": "APIs for integrating with FF provider",
    "title": "[CAL] FusionFlow as Provider",
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/users": {
      "post": {
        "description": "create User",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Create User",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RequestStruct"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/User"
            },
            "examples": {
              "application/json": {
                "id": 0,
                "username": "",
                "email": "",
                "created_at": "0001-01-01T00:00:00Z"
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "delete": {
        "description": "delete User",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Delete User",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of the resource",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/users/{uuid}": {
      "put": {
        "description": "update User",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Update User",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            },
            "examples": {
              "application/json": {
                "id": 0,
                "username": "",
                "email": "",
                "created_at": "0001-01-01T00:00:00Z"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "RequestStruct": {
      "type": "object",
      "required": [
        "id"
      ],
      "properties": {
        "email": {
          "description": "User's email address",
          "type": "string"
        },
        "first_name": {
          "description": "First name of the user",
          "type": "string"
        },
        "id": {
          "description": "Unique identifier for the user",
          "type": "integer",
          "format": "int64"
        },
        "last_name": {
          "description": "Last name of the user",
          "type": "string"
        },
        "username": {
          "description": "Username for login",
          "type": "string"
        }
      }
    },
    "UpdateUserRequest": {
      "type": "object",
      "properties": {
        "update_email": {
          "description": "Update the email of the user",
          "type": "string"
        },
        "update_username": {
          "description": "Update the username of the user",
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "description": "description=User's email address;example=john@example.com;required=true",
          "type": "string"
        },
        "id": {
          "description": "description=Unique identifier for the user;example=1;required=true",
          "type": "integer",
          "format": "int64"
        },
        "username": {
          "description": "description=Username for login;example=john_doe;required=true;format=email",
          "type": "string"
        }
      }
    }
  }
}